/**
 * Removes everything a test run creates, keying off the two dedicated
 * test-fixture accounts (`*@umeblog.test`, see scripts/seed-test-users.ts)
 * rather than fragile title-substring matching — every post/reply a test
 * ever creates is authored by one of those two accounts, so this is exact.
 *
 * Run after every CI test run (`if: always()`, so it happens even when a
 * test fails) since CI shares the real database with local dev and
 * production — there is no separate test database.
 */
import { inArray, like } from "drizzle-orm";
import { db } from "../src/lib/db";
import * as schema from "../src/lib/db/schema";

async function main() {
  const testUsers = await db.query.users.findMany({
    where: like(schema.users.email, "%@umeblog.test"),
  });
  const ids = testUsers.map((u) => u.id);

  if (ids.length > 0) {
    // posts.authorId and replies.userId have no onDelete cascade (deleting a
    // real account must never silently delete its posts), so both need an
    // explicit delete before the users themselves. Posts cascade to their
    // own post_tags/replies/comments automatically once deleted.
    await db.delete(schema.replies).where(inArray(schema.replies.userId, ids));
    await db.delete(schema.posts).where(inArray(schema.posts.authorId, ids));
    await db.delete(schema.users).where(inArray(schema.users.id, ids));
  }

  // Not user-scoped (keyed by IP hash), so just clear it outright — every
  // row here was generated by a test run, real or CI.
  await db.delete(schema.loginAttempts);

  console.log(`cleaned up ${ids.length} test account(s), their content, and login_attempts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
