/**
 * Removes everything a test run creates, keying off the two dedicated
 * test-fixture accounts (`*@umeblog.test`, see scripts/seed-test-users.ts)
 * rather than fragile title-substring matching — every post/reply a test
 * ever creates is authored by one of those two accounts, so this is exact.
 *
 * Run after every CI test run (`if: always()`, so it happens even when a
 * test fails) since CI shares the real database with local dev and
 * production — there is no separate test database.
 */
import { and, eq, inArray, like, or } from "drizzle-orm";
import { db } from "../src/lib/db";
import * as schema from "../src/lib/db/schema";

// tests/search.spec.ts:14,41 and tests/blog.spec.ts:65 type these prefixes
// into /search, which logs a `search` event per hit
// (src/app/(public)/search/page.tsx). Change a prefix in either place and
// update it here too. Matched on the `meta` JSON's `q` field specifically
// (not a bare substring match) so a real query that happens to contain one
// of these strings is never swept up.
const TEST_QUERY_PREFIXES = ["検索テスト-", "該当なし-"];

// tests/blog.spec.ts and tests/e2e.spec.ts create tags with these prefixes.
// Unlike posts/replies, a tag's row doesn't cascade away when the test post
// that used it is deleted (post_tags does, tags itself doesn't) — without
// this, every test run leaves one more orphan tag behind, which is exactly
// the crowding /admin/tags' curation exists to prevent.
const TEST_TAG_PREFIXES = ["絞り込みタグ", "テストタグ-"];

async function main() {
  const testUsers = await db.query.users.findMany({
    where: like(schema.users.email, "%@umeblog.test"),
  });
  const ids = testUsers.map((u) => u.id);

  if (ids.length > 0) {
    // posts.authorId, replies.userId, and tickets.createdById have no onDelete
    // cascade (deleting a real account must never silently delete its posts
    // or ideas), so all three need an explicit delete before the users
    // themselves. Posts cascade to their own post_tags/replies/comments
    // automatically once deleted; tickets.linkedPostId is `set null`, so
    // deleting posts first never blocks on a linked ticket.
    await db.delete(schema.replies).where(inArray(schema.replies.userId, ids));
    await db.delete(schema.posts).where(inArray(schema.posts.authorId, ids));
    await db.delete(schema.tickets).where(inArray(schema.tickets.createdById, ids));
    await db.delete(schema.users).where(inArray(schema.users.id, ids));
  }

  // Not user-scoped (keyed by IP hash), so just clear it outright — every
  // row here was generated by a test run, real or CI.
  await db.delete(schema.loginAttempts);

  const deletedSearches = await db
    .delete(schema.events)
    .where(
      and(
        eq(schema.events.type, "search"),
        or(...TEST_QUERY_PREFIXES.map((p) => like(schema.events.meta, `%"q":"${p}%`))),
      ),
    )
    .returning({ id: schema.events.id });

  // Safe even though post_tags/ticket_tags cascade from tags.id: by the time
  // this runs, every test post/ticket that used these tags is already gone,
  // so a matching tag row here is always an orphan.
  const deletedTags = await db
    .delete(schema.tags)
    .where(or(...TEST_TAG_PREFIXES.map((p) => like(schema.tags.name, `${p}%`))))
    .returning({ id: schema.tags.id });

  console.log(
    `cleaned up ${ids.length} test account(s), their content, login_attempts, ${deletedSearches.length} test search event(s), and ${deletedTags.length} test tag(s)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
